//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MupenToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MupenToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog.
        /// </summary>
        public static string Analog {
            get {
                return ResourceManager.GetString("Analog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ang.
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mupen Toolkit.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Plugin Name.
        /// </summary>
        public static string AudioPluginName {
            get {
                return ResourceManager.GetString("AudioPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        public static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string AxisX {
            get {
                return ResourceManager.GetString("AxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string AxisY {
            get {
                return ResourceManager.GetString("AxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid magic cookie.
        /// </summary>
        public static string BadMagicCookie {
            get {
                return ResourceManager.GetString("BadMagicCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string ButtonA {
            get {
                return ResourceManager.GetString("ButtonA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string ButtonB {
            get {
                return ResourceManager.GetString("ButtonB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass.
        /// </summary>
        public static string BypassMovie {
            get {
                return ResourceManager.GetString("BypassMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed combo.
        /// </summary>
        public static string ComboEOFStringSearch {
            get {
                return ResourceManager.GetString("ComboEOFStringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed combo.
        /// </summary>
        public static string ComboOOBLength {
            get {
                return ResourceManager.GetString("ComboOOBLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 1.
        /// </summary>
        public static string Controller0 {
            get {
                return ResourceManager.GetString("Controller0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 2.
        /// </summary>
        public static string Controller1 {
            get {
                return ResourceManager.GetString("Controller1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 3.
        /// </summary>
        public static string Controller2 {
            get {
                return ResourceManager.GetString("Controller2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller 4.
        /// </summary>
        public static string Controller3 {
            get {
                return ResourceManager.GetString("Controller3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Amount.
        /// </summary>
        public static string ControllerBoundsCheck {
            get {
                return ResourceManager.GetString("ControllerBoundsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the controller amount is within logical bounds.
        /// </summary>
        public static string ControllerBoundsCheckDescription {
            get {
                return ResourceManager.GetString("ControllerBoundsCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string Controllers {
            get {
                return ResourceManager.GetString("Controllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cv.
        /// </summary>
        public static string CPadDown {
            get {
                return ResourceManager.GetString("CPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&lt;.
        /// </summary>
        public static string CPadLeft {
            get {
                return ResourceManager.GetString("CPadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&gt;.
        /// </summary>
        public static string CPadRight {
            get {
                return ResourceManager.GetString("CPadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C^.
        /// </summary>
        public static string CPadUp {
            get {
                return ResourceManager.GetString("CPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string DataDiagnosis {
            get {
                return ResourceManager.GetString("DataDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dv.
        /// </summary>
        public static string DPadDown {
            get {
                return ResourceManager.GetString("DPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&lt;.
        /// </summary>
        public static string DPadLeft {
            get {
                return ResourceManager.GetString("DPadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&gt;.
        /// </summary>
        public static string DPadRight {
            get {
                return ResourceManager.GetString("DPadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D^.
        /// </summary>
        public static string DPadUp {
            get {
                return ResourceManager.GetString("DPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped more than one file, the first will be considered and rest discarded..
        /// </summary>
        public static string DragDropTooMany {
            get {
                return ResourceManager.GetString("DragDropTooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic parser error.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse header.
        /// </summary>
        public static string HeaderParseFailed {
            get {
                return ResourceManager.GetString("HeaderParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Plugin Name.
        /// </summary>
        public static string InputPluginName {
            get {
                return ResourceManager.GetString("InputPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input buffer resulted logically impossible state.
        /// </summary>
        public static string InputsInvalidState {
            get {
                return ResourceManager.GetString("InputsInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse inputs.
        /// </summary>
        public static string InputsParseFailed {
            get {
                return ResourceManager.GetString("InputsParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Statistics.
        /// </summary>
        public static string InputStatistics {
            get {
                return ResourceManager.GetString("InputStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC-Compliant.
        /// </summary>
        public static string IsABC {
            get {
                return ResourceManager.GetString("IsABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether this input sequence complies with A-Button-Challenge.
        /// </summary>
        public static string IsABCDescription {
            get {
                return ResourceManager.GetString("IsABCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (Samples).
        /// </summary>
        public static string LengthSamples {
            get {
                return ResourceManager.GetString("LengthSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string LoadData {
            get {
                return ResourceManager.GetString("LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Last.
        /// </summary>
        public static string LoadLast {
            get {
                return ResourceManager.GetString("LoadLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Cookie.
        /// </summary>
        public static string MagicCookieCheck {
            get {
                return ResourceManager.GetString("MagicCookieCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the movie&apos;s magic cookie (signature leading 4 bytes) match the M64 format convention.
        /// </summary>
        public static string MagicCookieCheckDescription {
            get {
                return ResourceManager.GetString("MagicCookieCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mempak.
        /// </summary>
        public static string Mempak {
            get {
                return ResourceManager.GetString("Mempak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Controllers connected.
        /// </summary>
        public static string NoControllers {
            get {
                return ResourceManager.GetString("NoControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not a movie.
        /// </summary>
        public static string NotAMovie {
            get {
                return ResourceManager.GetString("NotAMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Old_Version {
            get {
                return ResourceManager.GetString("Old Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when pasting. Is your clipboard content in the correct format?.
        /// </summary>
        public static string PasteError {
            get {
                return ResourceManager.GetString("PasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File unavailable.
        /// </summary>
        public static string PathError {
            get {
                return ResourceManager.GetString("PathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerecords.
        /// </summary>
        public static string Rerecords {
            get {
                return ResourceManager.GetString("Rerecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM Country.
        /// </summary>
        public static string RomCountry {
            get {
                return ResourceManager.GetString("RomCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM Name.
        /// </summary>
        public static string RomName {
            get {
                return ResourceManager.GetString("RomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSP Plugin Name.
        /// </summary>
        public static string RSPPluginName {
            get {
                return ResourceManager.GetString("RSPPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumblepak.
        /// </summary>
        public static string Rumblepak {
            get {
                return ResourceManager.GetString("Rumblepak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save is misaligned!.
        /// </summary>
        public static string SaveAlignment {
            get {
                return ResourceManager.GetString("SaveAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region-Conformant VI/s.
        /// </summary>
        public static string StandardVISCheck {
            get {
                return ResourceManager.GetString("StandardVISCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether rounded VI/s conform to either PAL/NTSC standard.
        /// </summary>
        public static string StandardVISCheckDescription {
            get {
                return ResourceManager.GetString("StandardVISCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Type.
        /// </summary>
        public static string StartupTypeSanityCheck {
            get {
                return ResourceManager.GetString("StartupTypeSanityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the startup type is within logical bounds and known values.
        /// </summary>
        public static string StartupTypeSanityCheckDescription {
            get {
                return ResourceManager.GetString("StartupTypeSanityCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS Studio.
        /// </summary>
        public static string TASStudio {
            get {
                return ResourceManager.GetString("TASStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of {0} button held samples.
        /// </summary>
        public static string TimesPressedFormat {
            get {
                return ResourceManager.GetString("TimesPressedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} held.
        /// </summary>
        public static string TimesPressedFormatShort {
            get {
                return ResourceManager.GetString("TimesPressedFormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An inputted property &quot;{0}&quot; had an inappropriate length and has been truncated..
        /// </summary>
        public static string TooLongStringNotificationFormat {
            get {
                return ResourceManager.GetString("TooLongStringNotificationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie is too short.
        /// </summary>
        public static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Button Presses.
        /// </summary>
        public static string TotalButtonPresses {
            get {
                return ResourceManager.GetString("TotalButtonPresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount of buttons held on each frame.
        /// </summary>
        public static string TotalButtonPressesDescription {
            get {
                return ResourceManager.GetString("TotalButtonPressesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string TriggerL {
            get {
                return ResourceManager.GetString("TriggerL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string TriggerR {
            get {
                return ResourceManager.GetString("TriggerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string TriggerZ {
            get {
                return ResourceManager.GetString("TriggerZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string UnloadData {
            get {
                return ResourceManager.GetString("UnloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA/Japan.
        /// </summary>
        public static string USAJapan {
            get {
                return ResourceManager.GetString("USAJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Validity.
        /// </summary>
        public static string VersionCheck {
            get {
                return ResourceManager.GetString("VersionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the movies&apos; version is adequate to current standard.
        /// </summary>
        public static string VersionCheckDescription {
            get {
                return ResourceManager.GetString("VersionCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound VIs.
        /// </summary>
        public static string VIBoundsCheck {
            get {
                return ResourceManager.GetString("VIBoundsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether VIs are within logical bounds.
        /// </summary>
        public static string VIBoundsCheckDescription {
            get {
                return ResourceManager.GetString("VIBoundsCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Plugin Name.
        /// </summary>
        public static string VideoPluginName {
            get {
                return ResourceManager.GetString("VideoPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
