//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MupenToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MupenToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mupen Toolkit.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string Controllers {
            get {
                return ResourceManager.GetString("Controllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (Samples).
        /// </summary>
        public static string LengthSamples {
            get {
                return ResourceManager.GetString("LengthSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Movie.
        /// </summary>
        public static string LoadMovie {
            get {
                return ResourceManager.GetString("LoadMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rerecords.
        /// </summary>
        public static string Rerecords {
            get {
                return ResourceManager.GetString("Rerecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM Country.
        /// </summary>
        public static string RomCountry {
            get {
                return ResourceManager.GetString("RomCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM Name.
        /// </summary>
        public static string RomName {
            get {
                return ResourceManager.GetString("RomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Movie.
        /// </summary>
        public static string SaveMovie {
            get {
                return ResourceManager.GetString("SaveMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS Studio.
        /// </summary>
        public static string TASStudio {
            get {
                return ResourceManager.GetString("TASStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Movie.
        /// </summary>
        public static string UnloadMovie {
            get {
                return ResourceManager.GetString("UnloadMovie", resourceCulture);
            }
        }
    }
}
