name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
        
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
        
    - name: MSBuild
      run: |
          msbuild.exe MupenToolkit.sln /p:platform="x64" /p:configuration="Release"
          
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
          name: mupen-toolkit-artifact
          path: bin/x64/Release
          retention-days: 7
